
import { useState, useRef, useEffect } from 'react';

const Disclaimer = () => {
  const sectionRef = useRef<HTMLElement>(null);
  const [isVisible, setIsVisible] = useState(false);
  
  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true);
          observer.unobserve(entry.target);
        }
      },
      { threshold: 0.1 }
    );
    
    if (sectionRef.current) {
      observer.observe(sectionRef.current);
    }
    
    return () => {
      if (sectionRef.current) {
        observer.unobserve(sectionRef.current);
      }
    };
  }, []);

  return (
    <section id="disclaimer" ref={sectionRef} className="section-spacing relative">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Legal <span className="text-gradient">Disclaimer</span>
          </h2>
        </div>
        
        <div className={`max-w-4xl mx-auto glass-panel rounded-2xl p-6 md:p-8 ${isVisible ? 'animate-fade-in' : 'opacity-0'}`}>
          <div className="space-y-6 text-gray-300">
            <p>
              <strong>Educational Purpose Only:</strong> UBI Strategist GPT is provided for educational and informational purposes only. The analyses, recommendations, and projections generated by this tool should not be considered as professional financial, economic, legal, or policy advice.
            </p>
            
            <p>
              <strong>No Guarantees:</strong> While we strive for accuracy and comprehensiveness, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the information, products, services, or related graphics provided through UBI Strategist GPT.
            </p>
            
            <p>
              <strong>Not Official Policy:</strong> Any policy frameworks, funding mechanisms, or implementation strategies suggested by UBI Strategist GPT do not constitute official policy recommendations and should not be implemented without proper review by qualified professionals and relevant authorities.
            </p>
            
            <p>
              <strong>Data Limitations:</strong> Economic analyses and projections are subject to inherent limitations and uncertainties. Future economic conditions, policy changes, and societal developments may differ substantially from those projected by UBI Strategist GPT.
            </p>
            
            <p>
              <strong>No Liability:</strong> AI Web Tools LLC, its employees, partners, and affiliates shall not be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from the use of UBI Strategist GPT.
            </p>
            
            <p>
              <strong>Not Investment Advice:</strong> Nothing contained in UBI Strategist GPT constitutes investment, legal, tax, or other advice nor is it to be relied on in making an investment or other decision.
            </p>
            
            <p>
              <strong>User Responsibility:</strong> Users are responsible for verifying any information before relying on it. The decision to use any information or suggestions provided by UBI Strategist GPT rests solely with the user.
            </p>
            
            <p>
              <strong>Third-Party Links:</strong> UBI Strategist GPT may contain links to external websites or resources. We have no control over the nature, content, and availability of those sites. The inclusion of any links does not necessarily imply a recommendation or endorsement of the views expressed within them.
            </p>
            
            <p>
              By using UBI Strategist GPT, you acknowledge that you have read, understood, and agree to these disclaimers and limitations.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Disclaimer;
